# Generated by Django 4.1.7 on 2023-04-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0002_alter_outsideairtemp_outside_air_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideairtemp',
            name='outside_air_temp',
            field=models.FloatField(default=0.0),
        ),
    ]
