# Generated by Django 4.1.7 on 2023-04-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0003_alter_outsideairtemp_outside_air_temp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HumididtySetpoint',
            new_name='HumiditySetpoint',
        ),
    ]
