# Generated by Django 4.1.7 on 2023-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0004_rename_humididtysetpoint_humiditysetpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenValveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_valve_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GreenhousePlanterValveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenhouse_planter_valve_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GreenhouseTreeValveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenhouse_tree_valve_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Valve1Status',
        ),
    ]
