# Generated by Django 4.1.7 on 2023-04-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0005_gardenvalvestatus_greenhouseplantervalvestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenvalvestatus',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gardenvalvestatus',
            name='start_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gardenvalvestatus',
            name='start_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouseplantervalvestatus',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouseplantervalvestatus',
            name='start_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouseplantervalvestatus',
            name='start_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhousetreevalvestatus',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhousetreevalvestatus',
            name='start_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhousetreevalvestatus',
            name='start_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pumpstatus',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pumpstatus',
            name='start_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pumpstatus',
            name='start_minute',
            field=models.IntegerField(default=0),
        ),
    ]
