# Generated by Django 4.1.7 on 2023-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0006_gardenvalvestatus_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFrostGreenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
