# Generated by Django 4.1.7 on 2023-04-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0007_lastfrostgreenhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
