# Generated by Django 4.1.7 on 2023-04-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0009_pumpstatus_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpstatus',
            name='next_start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
