# Generated by Django 4.1.7 on 2023-04-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0010_pumpstatus_next_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpstatus',
            name='next_start_time',
            field=models.DateTimeField(),
        ),
    ]
