# Generated by Django 4.1.7 on 2023-05-01 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_greenhouse', '0011_alter_pumpstatus_next_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenvalvestatus',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gardenvalvestatus',
            name='next_start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 17, 0, 31, 553721)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenhouseplantervalvestatus',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhouseplantervalvestatus',
            name='next_start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 17, 0, 41, 50085)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenhousetreevalvestatus',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greenhousetreevalvestatus',
            name='next_start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 17, 0, 44, 802922)),
            preserve_default=False,
        ),
    ]
